http:
  port: 8080
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

redis:
  addr: localhost:6379
  numberDB: 0
  dialTimeout: 10s
  readTimeout: 10s
  writeTimeout: 10s
  poolSize: 10
  minIdleConns: 10

postgres:
  host: localhost
  port: 5432
  database: postgres
  sslMode: disable

jwt:
  accessTokenTTL: 15m
  refreshTokenTTL: 24h

smpt:
  smptHost: localhost
  smptPort: 1025
  smptUser: user
  smptPassword: password